
export const ADD_CREDENTIALS = 'ADD_CREDENTIALS'
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS'
export const ADD_PROFILE_ERROR = 'ADD_PROFILE_ERROR'
export const REMOVE_PROFILE_SUCCESS = 'REMOVE_PROFILE_SUCCESS'
export const REMOVE_PROFILE_ERROR = 'REMOVE_PROFILE_ERROR'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'
